### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by MJRICE256** [McRange/Material-Kanban-Board#1]
I notice that the plug-in does not fully work in IE11 - the error states 'Object does not support property of method 'find'.

Are there any plans to enhance the plug-in to work in this browser? It seems to work well in Chrome and Edge.

Thanks.

**Comment by McRange** [comment]
Hello,
The "find" method refers to Array.prototype.find()
[Hello,
The "find" method refers to Array.prototype.find()
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find
It is not planned to support IE yet, but would be possible. Is the problem still up to date? 
]
It is not planned to support IE yet, but would be possible. Is the problem still up to date?
