### ISSUE TITLE
APEX 19.1

### ISSUE THREAD

**Issue by jzzh** [McRange/Material-Kanban-Board#2]
Will this also be working with the 19.1 version of APEX ?

**Comment by rolandoarg** [comment]
I have the same doubt but for version 18.1

**Comment by McRange** [comment]
Hello,
The example app shows that it must also work with Apex 19.1. The plugin was initially developed with APEX 18.1.
 https://apex.oracle.com/pls/apex/f?p=PLUGINSBYRANGE:2
