### ISSUE TITLE
Section Drag and Drop PL/SQL Code and element value

### ISSUE THREAD

**Issue by gallis1** [McRange/Material-Kanban-Board#22]
Hi,

I want use element value in section Drag and Drop PL/SQL Code
For example, next line:
v_users_filt := :Pxx_USERS_FILT;

How can i do it?

Thanks

**Comment by McRange** [comment]
There is currently no clean binding of parameters in the plugin. 
However, you can use the V function to get the value of your ITEM:

`v_users_filt := V('Pxx_USERS_FILT');`
