### ISSUE TITLE
 Split a group in the column again into rows or groups?

### ISSUE THREAD

**Issue by FloMeh** [McRange/Material-Kanban-Board#24]
Hello,

is it possible to split a group in the column again into 3 rows or groups? I have sketched an example of this in the attached screenshot.

![image](https://user-images.githubusercontent.com/70646156/178230426-0ff3616a-2ef2-4f51-8e16-2549cf5f5982.png)

Thank you!

**Comment by McRange** [comment]
No, I haven't seen anything like that on any Kanban board yet.
