### ISSUE TITLE
kanban attributes, global variables access with problem

### ISSUE THREAD

**Issue by emazzu** [McRange/Material-Kanban-Board#28]
Hi gay, how are you ??
I have two global variables in Apex, :COMPANY and :APP_USER, but in kanban attributes, Drag and Drop -> Drag and Drop PL/SQL Code,  It doesn't allow me to use them ??

can this be possible? Are there any restrictions?

![image](https://github.com/McRange/Material-Kanban-Board/assets/6100546/be468e8a-dddb-4808-92c2-dcf2b2261b71)

**Comment by McRange** [comment]
Hi,
cause there is no additional variable binding, you have to use the V-function:

`DECLARE
    l_company := V('COMPANY');
    l_user := V('APP_USER');
BEGIN ...
`
