### ISSUE TITLE
APEX versions 19.1

### ISSUE THREAD

**Issue by bramorim** [McRange/Material-Kanban-Board#6]
Hi,

Is the Kanban compatible with Apex Version 19.1?

If not, exists a date?

Tks, Bruno

**Comment by Geri1590** [comment]
It worked for me on 19.1, 19.2 and 20.1

**Comment by Marcos-Branquinho** [comment]
I'm trying to import the Plugin on Oracle APEX 20.2 but it's not working, any suggestions?

**Comment by McRange** [comment]
Plugin works up to APEX 23.2
