### ISSUE TITLE
Automatically update by event

### ISSUE THREAD

**Issue by jekeam** [McRange/Material-Kanban-Board#9]
How can I update the Board for everyone if the user moved the map? Probably this is implemented through webhooks, there is some built-in mechanism or my needs to come up with it yourself? What do you advise?

**Comment by SergioRomera** [comment]
I have the same problem. How can we update the value in the table?.
Thanks in advance. Your Kanban board is great!.

**Comment by jekeam** [comment]
> I have the same problem. How can we update the value in the table?.
> Thanks in advance. Your Kanban board is great!.

I'm using a temporary solution out of the box, updating the board, every Х seconds

**Comment by McRange** [comment]
This is a global problem in APEX / Oracle. There is no build in solution for updating any content pushed by server. APEX always need a client side interaction.
